### PR TITLE
Test PR

### PR DESCRIPTION
**Pull request by EspeuteClement**

### CODE REVIEW

**Comment by lut0pia** [comment]
Good idea to add the guideline for contributing data but I disagree with the example you gave, that's actually an entry I'm not very happy with. I'm fine with keeping the entry because it makes sense but I sense it's not a great example to give because it's already a bit far fetched, the best example would be something with an explicit value in it, not an implicit one.

Also, I don't understand the duration you gave for the entry:
`{type:'book', title:'One Thousand and One Nights', number:1001, duration:'12012d'}`

**Comment by EspeuteClement** [comment]
> Also, I don't understand the duration you gave for the entry:
> `{type:'book', title:'One Thousand and One Nights', number:1001, duration:'12012d'}`

My bad, It should have been 12012h if we want to have the duration of 1001 nights, or 1001d if we want to use the whole time between the first and the last night as a time reference

**Comment by lut0pia** [comment]
Alright, for simplicity's sake I would go for 1001 days, but your approach doesn't seem any less valid. However if we want to apply your vision of duration for the entry, I'd suggest adding support for non-integers in the parsing mechanism so we can write `500.5d` which sounds a *bit* more understandable than the hour count. We can go with the hour count for now and I'll work on that feature later.

**Comment by EspeuteClement** [comment]
I think that dates with periods such as `500.5d` are broken with the current parser

**Comment by lut0pia** [comment]
That's what I was saying, yes.

**Pull request closed without merging**
